content = (
    "import numpy as np\n"
    "\n"
    "\n"
    "def eci_to_lla(x: float, y: float, z: float, gst: float) -> dict:\n"
    "    \"\"\"\n"
    "    Convert ECI coordinates to latitude, longitude, altitude.\n"
    "\n"
    "    Args:\n"
    "        x, y, z: ECI position in km\n"
    "        gst: Greenwich Sidereal Time in radians\n"
    "\n"
    "    Returns:\n"
    "        dict with lat, lon, alt\n"
    "    \"\"\"\n"
    "    R_EARTH = 6378.137\n"
    "    e2 = 0.00669437999014\n"
    "\n"
    "    lon = np.arctan2(y, x) - gst\n"
    "    lon = (np.degrees(lon) + 360) % 360\n"
    "    if lon > 180:\n"
    "        lon -= 360\n"
    "\n"
    "    r = np.sqrt(x**2 + y**2)\n"
    "    lat = np.arctan2(z, r)\n"
    "\n"
    "    for _ in range(5):\n"
    "        sin_lat = np.sin(lat)\n"
    "        N = R_EARTH / np.sqrt(1 - e2 * sin_lat**2)\n"
    "        lat = np.arctan2(z + e2 * N * sin_lat, r)\n"
    "\n"
    "    lat = np.degrees(lat)\n"
    "    sin_lat = np.sin(np.radians(lat))\n"
    "    N = R_EARTH / np.sqrt(1 - e2 * sin_lat**2)\n"
    "    alt = r / np.cos(np.radians(lat)) - N\n"
    "\n"
    "    return {'lat': lat, 'lon': lon, 'alt': alt}\n"
    "\n"
    "\n"
    "def gst_from_jd(jd: float, fr: float) -> float:\n"
    "    \"\"\"\n"
    "    Compute Greenwich Sidereal Time from Julian date.\n"
    "\n"
    "    Args:\n"
    "        jd: Julian date\n"
    "        fr: fractional day\n"
    "\n"
    "    Returns:\n"
    "        GST in radians\n"
    "    \"\"\"\n"
    "    T = ((jd + fr) - 2451545.0) / 36525.0\n"
    "    gst = (67310.54841\n"
    "           + (876600 * 3600 + 8640184.812866) * T\n"
    "           + 0.093104 * T**2\n"
    "           - 6.2e-6 * T**3)\n"
    "    gst = np.radians(gst / 240.0 % 360.0)\n"
    "    return gst\n"
)

with open('src/transforms.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done")