content = (
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.image as mpimg\n"
    "import numpy as np\n"
    "from datetime import datetime, timezone, timedelta\n"
    "from sgp4.api import jday\n"
    "import sys\n"
    "sys.path.insert(0, 'src')\n"
    "from tle_parser import parse_tle\n"
    "from propagator import propagate\n"
    "from transforms import eci_to_lla, gst_from_jd\n"
    "\n"
    "\n"
    "RAW_TLE = \"\"\"ISS (ZARYA)\n"
    "1 25544U 98067A   24001.50000000  .00002182  00000-0  40768-4 0  9990\n"
    "2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.50377579404740\"\"\"\n"
    "\n"
    "\n"
    "def get_ground_track(raw_tle: str, minutes: int = 92) -> list[dict]:\n"
    "    tle = parse_tle(raw_tle)\n"
    "    start = datetime(2024, 1, 1, 12, 0, 0, tzinfo=timezone.utc)\n"
    "    times = [start + timedelta(seconds=60*i) for i in range(minutes)]\n"
    "    results = propagate(tle, times)\n"
    "\n"
    "    track = []\n"
    "    for r in results:\n"
    "        t = r['time']\n"
    "        jd, fr = jday(t.year, t.month, t.day, t.hour, t.minute, t.second)\n"
    "        gst = gst_from_jd(jd, fr)\n"
    "        lla = eci_to_lla(r['x'], r['y'], r['z'], gst)\n"
    "        track.append(lla)\n"
    "\n"
    "    return track\n"
    "\n"
    "\n"
    "def plot_ground_track(track: list[dict]) -> None:\n"
    "    lats = [p['lat'] for p in track]\n"
    "    lons = [p['lon'] for p in track]\n"
    "\n"
    "    fig, ax = plt.subplots(figsize=(14, 7))\n"
    "    ax.set_facecolor('#0d1b2a')\n"
    "    fig.patch.set_facecolor('#0d1b2a')\n"
    "\n"
    "    ax.set_xlim(-180, 180)\n"
    "    ax.set_ylim(-90, 90)\n"
    "    ax.set_xlabel('Longitude', color='white')\n"
    "    ax.set_ylabel('Latitude', color='white')\n"
    "    ax.tick_params(colors='white')\n"
    "    ax.set_title('ISS Ground Track — One Orbit', color='white', fontsize=14)\n"
    "\n"
    "    ax.plot(lons, lats, color='#00d4ff', linewidth=1.5, label='Ground Track')\n"
    "    ax.plot(lons[0], lats[0], 'o', color='#00ff88', markersize=8, label='Start')\n"
    "    ax.plot(lons[-1], lats[-1], 'o', color='#ff4444', markersize=8, label='End')\n"
    "\n"
    "    ax.gridlines = ax.grid(color='white', alpha=0.1)\n"
    "    ax.legend(facecolor='#0d1b2a', labelcolor='white')\n"
    "\n"
    "    plt.tight_layout()\n"
    "    plt.savefig('ground_track.png', dpi=150, bbox_inches='tight')\n"
    "    plt.show()\n"
    "    print('Saved to ground_track.png')\n"
    "\n"
    "\n"
    "if __name__ == '__main__':\n"
    "    track = get_ground_track(RAW_TLE)\n"
    "    plot_ground_track(track)\n"
)

with open('src/visualizer.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done")