content = (
    "from sgp4.api import Satrec, WGS72, jday\n"
    "from datetime import datetime, timezone\n"
    "import numpy as np\n"
    "\n"
    "from tle_parser import TLE\n"
    "\n"
    "\n"
    "def build_satellite(tle: TLE) -> Satrec:\n"
    "    return Satrec.twoline2rv(tle.line1, tle.line2)\n"
    "\n"
    "\n"
    "def propagate(tle: TLE, times: list[datetime]) -> list[dict]:\n"
    "    satellite = build_satellite(tle)\n"
    "    results = []\n"
    "\n"
    "    for t in times:\n"
    "        jd, fr = jday(t.year, t.month, t.day, t.hour, t.minute, t.second)\n"
    "        error, position, velocity = satellite.sgp4(jd, fr)\n"
    "\n"
    "        if error != 0:\n"
    "            print(f'SGP4 error code {error} at {t}')\n"
    "            continue\n"
    "\n"
    "        results.append({\n"
    "            'time': t,\n"
    "            'x': position[0],\n"
    "            'y': position[1],\n"
    "            'z': position[2],\n"
    "            'vx': velocity[0],\n"
    "            'vy': velocity[1],\n"
    "            'vz': velocity[2],\n"
    "        })\n"
    "\n"
    "    return results\n"
)

with open('src/propagator.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done")